# Generated by Django 5.0.6 on 2024-07-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='foods',
            field=models.ManyToManyField(blank=True, to='hotel_app.food'),
        ),
    ]
