# Generated by Django 5.0.6 on 2024-07-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_alter_hotel_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
