# Generated by Django 5.0.6 on 2024-07-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_alter_hotel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='earn',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
