# Generated by Django 5.0.6 on 2024-07-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('order placed', 'order placed'), ('out for delivery', 'out for delivery'), ('delivery compleated', 'delivery compleated')], default=('pending', 'pending'), max_length=250),
        ),
    ]
