# Generated by Django 5.0.6 on 2024-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_userorder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
