# Generated by Django 5.0.6 on 2024-07-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_userorder_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='delivery_b',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
