# Generated by Django 5.0.6 on 2024-07-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_userorder_delivery_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='payment_type',
            field=models.CharField(choices=[('online_pay', 'Online Payment'), ('COD', 'Cash on Delivery')], max_length=250),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('order_placed', 'Order Placed'), ('out_for_delivery', 'Out for Delivery'), ('delivery_completed', 'Delivery Completed')], default=('pending', 'Pending'), max_length=250),
        ),
    ]
