# Generated by Django 5.0.6 on 2024-07-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deluser',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
