# Generated by Django 5.0.6 on 2024-07-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_alter_deluser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='deluser',
            name='earn',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deluser',
            name='floating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
